### ISSUE TITLE
YOLOv5-n配置文件默认batch size是8/GPU

### ISSUE THREAD

**Issue by firedent** [nemonameless/PaddleDetection_YOLOv5#2]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

README中给出的YOLOv5-n batch size为：16/GPU，但是按照当前配置文件，batch size为：8/GPU。
是否应该在[yolov5_n_300e_coco.yml](https://github.com/nemonameless/PaddleDetection_YOLOv5/blob/develop/configs/yolov5/yolov5_n_300e_coco.yml)中单独指定batch size和lr？

**Comment by nemonameless** [comment]
是的config里改好了，谢谢反馈~
