### ISSUE TITLE
YOLOv5训练精度低的问题

### ISSUE THREAD

**Issue by fan-min-97** [nemonameless/PaddleDetection_YOLOv5#3]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

您好，这个是paddle复现的yolov5吗？我在用yolov5训练数据集的时候（烟雾火灾两类），准确度一直上不去，300轮map(0.5,11point)=43%左右，这个是什么问题呢？用voc和coco两种训练集，精度都上不去呢。望回复(⊙︿⊙)

**Comment by nemonameless** [comment]
有和其他模型精度对比吗？几卡训的，配置文件改了什么？
训自己的数据集，建议加载coco训好的权重做预训练。

**Comment by fan-min-97** [comment]
您好，跑过paddle上有人复现的yolov5，那时候能跑到70左右；VOC格式。
单卡训练，用的是paddle 1点/1小时。配置文件改了训练的batch_size=4，还有就是voc.yml，yolov5读取训练数据的配置文件。其他没改动。

**Comment by nemonameless** [comment]
注意加载coco预训练去训了吗？建议先排查下训练过程loss变化过程。此代码库需要8卡bs=64左右才迅速收敛达到高精度，如果单卡总bs只有4实在过小了。
其他paddle版本yolov5，是指几乎全部改torch接口为paddle的实现吗？可能保留了一些torch单卡多卡随bs动态超参变化的trick。
